### ISSUE TITLE
wallpanel stoped working on all clients

### ISSUE THREAD

**Issue by bbsopar** [j-a-n/lovelace-wallpanel#261]
Few day before I've done update of HA and wallpanel and yesterday noticed that wallpanel compleately stoped working on all clients. I 'ce tried to clear browsing cashe, I've tried with minimal wallpanel configuration but without sucsess to get it back working.
In log there is a following error:

wallpanel version: 4.25.5
HA Core 2024.7.4
HA Frontend 20240710.0

Logger: frontend.js.latest.202407100
Source: components/system_log/__init__.py:333
First occurred: August 2, 2024 at 20:50:57 (106 occurrences)
Last logged: 10:49:45

Uncaught error from Edge 127.0.0.0 on Windows 10 TypeError: this.createCardElement is not a function /local/wallpanel.js:866:30 WallpanelView.createInfoBoxContent (/local/wallpanel.js:857:17) WallpanelView.reconfigure (/local/wallpanel.js:1167:8) updateConfig (/local/wallpanel.js:270:14) activateWallpanel (/local/wallpanel.js:1526:2) /local/wallpanel.js:1566:4
Uncaught error from Edge 127.0.0.0 on Windows 10 TypeError: this.createCardElement is not a function /local/wallpanel.js:866:30 WallpanelView.createInfoBoxContent (/local/wallpanel.js:857:17) WallpanelView.startScreensaver (/local/wallpanel.js:1371:8) WallpanelView.timer (/local/wallpanel.js:589:10)
Uncaught error from Chrome WebView 126.0.6478.186 on Android 14 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "wallpanel-view" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2462:17)
Uncaught error from Chrome WebView 126.0.6478.186 on Android 14 TypeError: this.createCardElement is not a function /local/wallpanel.js:866:30 WallpanelView.createInfoBoxContent (/local/wallpanel.js:857:17) WallpanelView.reconfigure (/local/wallpanel.js:1167:8) updateConfig (/local/wallpanel.js:270:14) activateWallpanel (/local/wallpanel.js:1526:2) /local/wallpanel.js:1566:4
Uncaught error from Chrome WebView 126.0.6478.186 on Android 14 TypeError: this.createCardElement is not a function /local/wallpanel.js:866:30 WallpanelView.createInfoBoxContent (/local/wallpanel.js:857:17) WallpanelView.startScreensaver (/local/wallpanel.js:1371:8) WallpanelView.timer (/local/wallpanel.js:589:10)

**Comment by j-a-n** [comment]
Hello,

please verify that you are using the latest wallpanel version and clear your browser cache.

**Comment by Yo59** [comment]
Hi @bbsopar,

Did you find a solution? 
Wallpanel stop working also for me.

**Comment by bbsopar** [comment]
Still not, j-a-n replied to me few days ago withbsugestion to check
versions of plugin and to clear browser cashe. I'we tried that and checked
already before posting an issue, but without sucsess.
Curently I'm o  vacation and not able to try something else i.e. new HA
version or...

pet, 9. kol 2024. 18:39 Yo59 ***@***.***> je napisao:

**Comment by j-a-n** [comment]
Please try if the latest version 4.25.6 fixes the problem.
If not, please look for error messages in the browser console (F12) and post them here.

**Comment by bbsopar** [comment]
I will try in next few days and reply. Tomorow I'm coming home from
vacation and I will try.

Best regards
Branimir

ned, 11. kol 2024. 13:32 Jan Schneider ***@***.***> je
napisao:

**Comment by bbsopar** [comment]
I've upgraded wallpanel today through regular HACS procedure to latest version 4.25.6
HA assistant I'm still using previous version from 2024-07 since I see increased number of posts of users after upgrade to 2024-08 version and I prefer to wait until new version will be "more mature"
HA Core 2024.7.4
HA Frontend 20240710.0

Browser console shows following errors:

Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "wallpanel-view" has already been used with this registry
    at window.CustomElementRegistry.define (http://192.168.222.30:8123/frontend_latest/app.hoOvmAWTvos.js:2:4362)
    at startup (http://192.168.222.30:8123/hacsfiles/lovelace-wallpanel/wallpanel.js?hacstag=3095064164256:2471:17)
:8123/unknown/src/sc…ement-registry.js:1 
 
 Failed to load resource: the server responded with a status of 404 (Not Found)
wallpanel.js:866 
 Uncaught 
TypeError: this.createCardElement is not a function
    at wallpanel.js:866:30
    at Array.forEach (<anonymous>)
    at WallpanelView.createInfoBoxContent (wallpanel.js:857:17)
    at WallpanelView.reconfigure (wallpanel.js:1167:8)
    at updateConfig (wallpanel.js:270:14)
    at activateWallpanel (wallpanel.js:1526:2)
    at wallpanel.js:1566:4
wallpanel.js:462 
 Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.
wallpanel.js:866 
 Uncaught 
TypeError: this.createCardElement is not a function
    at wallpanel.js:866:30
    at Array.forEach (<anonymous>)
    at WallpanelView.createInfoBoxContent (wallpanel.js:857:17)
    at WallpanelView.startScreensaver (wallpanel.js:1371:8)
    at WallpanelView.timer (wallpanel.js:589:10)
wallpanel.js:467 
 
TypeError: Permissions check failed
    at enterFullscreen (wallpanel.js:462:6)
    at WallpanelView.setupScreensaver (wallpanel.js:1335:4)
    at WallpanelView.startScreensaver (wallpanel.js:1350:8)
    at WallpanelView.timer (wallpanel.js:589:10)
wallpanel.js:448 
 Failed to enter fullscreen
wallpanel.js?hacstag=3095064164256:304 
 Failed to enter fullscreen
wallpanel.js:462 
 Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.
wallpanel.js:866 
 Uncaught 
TypeError: this.createCardElement is not a function
    at wallpanel.js:866:30
    at Array.forEach (<anonymous>)
    at WallpanelView.createInfoBoxContent (wallpanel.js:857:17)
    at WallpanelView.startScreensaver (wallpanel.js:1371:8)
    at WallpanelView.timer (wallpanel.js:589:10)
wallpanel.js:467 
 
TypeError: Permissions check failed
    at enterFullscreen (wallpanel.js:462:6)
    at WallpanelView.setupScreensaver (wallpanel.js:1335:4)
    at WallpanelView.startScreensaver (wallpanel.js:1350:8)
    at WallpanelView.timer (wallpanel.js:589:10)
wallpanel.js:448 
 Failed to enter fullscreen
wallpanel.js?hacstag=3095064164256:304 
 Failed to enter fullscreen


I hope it helps...

**Comment by j-a-n** [comment]
Does the problem still exist or can the issue be closed?

**Comment by bbsopar** [comment]
I think not,
a few days ago I posted (on  wallpanel stoped working on all clients ·
Issue #261 · j-a-n/lovelace-wallpanel (github.com)
<https://github.com/j-a-n/lovelace-wallpanel/issues/261>  ) a debug window
from the browser, having installed HA Core 2024.7.4, HA Frontend 20240710.0
and wallpanel 4.25.6.

Today I upgraded HA (2024.8.2) and wallpanel (4.26.0) but issue still
persists (I cleared browser cache)
Here is latest debug log from browser:

Uncaught DOMException: Failed to execute 'define' on
'CustomElementRegistry': the name "wallpanel-view" has already been used
with this registry
    at window.CustomElementRegistry.define (
http://192.168.222.30:8123/frontend_latest/app.okM55PX7yEE.js:2:4271)
    at startup (
http://192.168.222.30:8123/hacsfiles/lovelace-wallpanel/wallpanel.js?hacstag=3095064164260:2481:17
)
:8123/unknown/src/sc…ement-registry.js:1

 Failed to load resource: the server responded with a status of 404 (Not
Found)
wallpanel.js:866
 Uncaught
TypeError: this.createCardElement is not a function
    at wallpanel.js:866:30
    at Array.forEach (<anonymous>)
    at WallpanelView.createInfoBoxContent (wallpanel.js:857:17)
    at WallpanelView.reconfigure (wallpanel.js:1167:8)
    at updateConfig (wallpanel.js:270:14)
    at activateWallpanel (wallpanel.js:1526:2)
    at wallpanel.js:1566:4
wallpanel.js:462
 Failed to execute 'requestFullscreen' on 'Element': API can only be
initiated by a user gesture.
wallpanel.js:866
 Uncaught
TypeError: this.createCardElement is not a function
    at wallpanel.js:866:30
    at Array.forEach (<anonymous>)
    at WallpanelView.createInfoBoxContent (wallpanel.js:857:17)
    at WallpanelView.startScreensaver (wallpanel.js:1371:8)
    at WallpanelView.timer (wallpanel.js:589:10)
wallpanel.js:467

TypeError: Permissions check failed
    at enterFullscreen (wallpanel.js:462:6)
    at WallpanelView.setupScreensaver (wallpanel.js:1335:4)
    at WallpanelView.startScreensaver (wallpanel.js:1350:8)
    at WallpanelView.timer (wallpanel.js:589:10)
wallpanel.js:448
 Failed to enter fullscreen
wallpanel.js?hacstag=3095064164260:304
 Failed to enter fullscreen
wallpanel.js:462
 Failed to execute 'requestFullscreen' on 'Element': API can only be
initiated by a user gesture.
wallpanel.js:866
 Uncaught
TypeError: this.createCardElement is not a function
    at wallpanel.js:866:30
    at Array.forEach (<anonymous>)
    at WallpanelView.createInfoBoxContent (wallpanel.js:857:17)
    at WallpanelView.startScreensaver (wallpanel.js:1371:8)
    at WallpanelView.timer (wallpanel.js:589:10)
wallpanel.js:467

TypeError: Permissions check failed
    at enterFullscreen (wallpanel.js:462:6)
    at WallpanelView.setupScreensaver (wallpanel.js:1335:4)
    at WallpanelView.startScreensaver (wallpanel.js:1350:8)
    at WallpanelView.timer (wallpanel.js:589:10)
wallpanel.js:448
 Failed to enter fullscreen
wallpanel.js?hacstag=3095064164260:304
 Failed to enter fullscreen
[NEW] Explain Console errors by using Copilot in Edge: click
 to explain an error. Learn more
Don't show again
5
Third-party cookie will be blocked in future Microsoft Edge versions as
part of unpartitioned third-party cookie deprecation.
wallpanel.js:462
 Failed to execute 'requestFullscreen' on 'Element': API can only be
initiated by a user gesture.
wallpanel.js:866
 Uncaught
TypeError: this.createCardElement is not a function
    at wallpanel.js:866:30
    at Array.forEach (<anonymous>)
    at WallpanelView.createInfoBoxContent (wallpanel.js:857:17)
    at WallpanelView.startScreensaver (wallpanel.js:1371:8)
    at WallpanelView.timer (wallpanel.js:589:10)
wallpanel.js:467

TypeError: Permissions check failed
    at enterFullscreen (wallpanel.js:462:6)
    at WallpanelView.setupScreensaver (wallpanel.js:1335:4)
    at WallpanelView.startScreensaver (wallpanel.js:1350:8)
    at WallpanelView.timer (wallpanel.js:589:10)
wallpanel.js:448
 Failed to enter fullscreen
wallpanel.js?hacstag=3095064164260:304
 Failed to enter fullscreen

**Comment by j-a-n** [comment]
These logs are not from the latest wallpanel version.
Please check your browser cache again.
You can also try to reinstall wallpanel.

**Comment by bbsopar** [comment]
Please can you point me what to look in browser log to be sure that browser
is loading correct wallpanel version?
Now I checked config www folder of HA server, and found wallpanel.js file
in root of config\www\
and there is now subfolder
config\www\community\lovelace-wallpanel\ containing wallpanel.js and
wallpanel.js.gz dated today.
Could that be an issue?

**Comment by j-a-n** [comment]
Yes, please delete the config/www/wallpanel.js file.
The running wallpanel version is logged to the browser console (dev tools / F12).

**Comment by bbsopar** [comment]
I works,
I renamed wallpanel.js file in root of www server folder, cleared browser
cashe and it works.
It is probably remains of some initial wallpanel installation.

Thank you for assistance and a very useful plugin.

Br
Branimir
