### ISSUE TITLE
Wall panel stop working after updating to 2024.6.0

### ISSUE THREAD

**Issue by tobalowar** [j-a-n/lovelace-wallpanel#235]
After updating home assistant to 2024.6.0 the screen saver stop working at all. In console logs appear the following error:

``Uncaught TypeError: this.createCardElement is not a function
    at wallpanel.js?hacstag=3095064164251:1145:30
    at Array.forEach (<anonymous>)
    at WallpanelView.createInfoBoxContent (wallpanel.js?hacstag=3095064164251:1132:17)
    at WallpanelView.startScreensaver (wallpanel.js?hacstag=3095064164251:2089:8)
    at WallpanelView.timer (wallpanel.js?hacstag=3095064164251:769:10)``

![image](https://github.com/j-a-n/lovelace-wallpanel/assets/16564706/af342a12-0c05-42ea-b074-6f3e8bd70245)

The version that i have is v4.25.1

**Comment by alfredolvera** [comment]
Same issue here, same behavior on 2 android tablets and a nest hub using catt.

**Comment by teadragon7** [comment]
Same issue

**Comment by danielxb-ar** [comment]
The same

**Comment by mukul-k** [comment]
also the same after updating!

**Comment by TN-1** [comment]
Can also confirm this issue. Raspberry Pi 3B+ with a touch screen running Raspberry Pi OS 64 Bit

**Comment by j-a-n** [comment]
Thanks for reporting.
This is fixed with version 4.25.2

**Comment by TN-1** [comment]
Thanks for the fix! Confirm it is working well with 2024.6.0

**Comment by Rafaille** [comment]
Hi,
still not working for me after updating to 4.25.2

I get pretty much the same error as the OP

`Uncaught error from Chrome WebView 120.0.6099.144 on Android 13 TypeError: this.createCardElement is not a function /hacsfiles/lovelace-wallpanel/wallpanel.js:1145:30 WallpanelView.createInfoBoxContent (/hacsfiles/lovelace-wallpanel/wallpanel.js:1132:17) WallpanelView.startScreensaver (/hacsfiles/lovelace-wallpanel/wallpanel.js:2078:8) WallpanelView.timer (/hacsfiles/lovelace-wallpanel/wallpanel.js:769:10)
Uncaught error from Chrome WebView 120.0.6099.144 on Android 13 TypeError: this.createCardElement is not a function /hacsfiles/lovelace-wallpanel/wallpanel.js:1145:30 WallpanelView.createInfoBoxContent (/hacsfiles/lovelace-wallpanel/wallpanel.js:1132:17) WallpanelView.updateScreensaver (/hacsfiles/lovelace-wallpanel/wallpanel.js:2144:9) WallpanelView.timer (/hacsfiles/lovelace-wallpanel/wallpanel.js:765:9)`

**Comment by formatBCE** [comment]
@Rafaille are you sure you cleared the cache? It works for me.

**Comment by danielxb-ar** [comment]
This works very well for me (sorry my english please)
after download "wallpanel.js" change name to "wallpaneljs4252.js"
in HA resources change the file name, restar HA

**Comment by Rafaille** [comment]
> @Rafaille are you sure you cleared the cache? It works for me.

Cache clearing, I keep forgetting about this one.
Will try and report asap
Thanks

**Comment by Rafaille** [comment]
It did the trick!
My bad... thanks for your help
